apiVersion: v1
kind: Service
metadata:
  name: job-posts-api-service
spec:
  type: NodePort
  selector:
      app: job-posts-api-label
  ports:
    - name: job-posts-service-np
      protocol: TCP
      port: 8080
      targetPort: 8080
