apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-posts-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-posts-ui-label
  template:
    metadata:
      labels:
        app: job-posts-ui-label
    spec:
      containers:
          - name: job-posts-ui
            image: byorn/job-post-ui:0.0.1