apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-posts-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-posts-api-label
  template:
    metadata:
      labels:
        app: job-posts-api-label
    spec:
      containers:
          - name: job-posts-api
            image: byorn/job-posts-api:latest